// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-refined/BlueprintTechnical.tsx": () => import("../components/mockups/homepage-refined/BlueprintTechnical.tsx"),
  "./components/mockups/homepage-refined/CommandCenter.tsx": () => import("../components/mockups/homepage-refined/CommandCenter.tsx"),
  "./components/mockups/homepage-refined/CyanDominant.tsx": () => import("../components/mockups/homepage-refined/CyanDominant.tsx"),
  "./components/mockups/homepage-refined/EditorialCinematic.tsx": () => import("../components/mockups/homepage-refined/EditorialCinematic.tsx"),
  "./components/mockups/homepage-refined/FieldReady.tsx": () => import("../components/mockups/homepage-refined/FieldReady.tsx"),
  "./components/mockups/homepage-refined/GroundedAuthority.tsx": () => import("../components/mockups/homepage-refined/GroundedAuthority.tsx"),
  "./components/mockups/homepage-refined/OrangeDominant.tsx": () => import("../components/mockups/homepage-refined/OrangeDominant.tsx"),
  "./components/mockups/homepage-refined/PolishedAuthority.tsx": () => import("../components/mockups/homepage-refined/PolishedAuthority.tsx"),
  "./components/mockups/homepage-refined/RefinedRhythm.tsx": () => import("../components/mockups/homepage-refined/RefinedRhythm.tsx"),
  "./components/mockups/homepage-refined/TightenedHierarchy.tsx": () => import("../components/mockups/homepage-refined/TightenedHierarchy.tsx"),
  "./components/mockups/homepage-refined/WarmSteel.tsx": () => import("../components/mockups/homepage-refined/WarmSteel.tsx")
};
