// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/homepage-refined/GroundedAuthority.tsx": () => import("../components/mockups/homepage-refined/GroundedAuthority.tsx"),
  "./components/mockups/homepage-refined/RefinedRhythm.tsx": () => import("../components/mockups/homepage-refined/RefinedRhythm.tsx"),
  "./components/mockups/homepage-refined/TightenedHierarchy.tsx": () => import("../components/mockups/homepage-refined/TightenedHierarchy.tsx"),
  "./components/mockups/homepage-refined/WarmSteel.tsx": () => import("../components/mockups/homepage-refined/WarmSteel.tsx")
};
